//actions
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SINGOUT_SUCCESS = 'SINGOUT_SUCCESS';

export const ADD_NEW_MEDICINE_SUCCESS = 'ADD_NEW_MEDICINE_SUCCESS';
export const ADD_NEW_MEDICINE_ERROR = 'ADD_NEW_MEDICINE_ERROR';
export const DELETE_MEDICINE_SUCCESS = 'DELETE_MEDICINE_SUCCESS';
export const UPDATE_MEDICINE_SUCCESS = 'UPDATE_MEDICINE_SUCCESS';
export const UPDATE_MEDICINE_ERROR = 'UPDATE_MEDICINE_ERROR';

export const ADD_NEW_TEAM_MEMBER_SUCCESS = 'ADD_NEW_TEAM_MEMBER_SUCCESS';
export const ADD_NEW_TEAM_MEMBER_ERROR = 'ADD_NEW_TEAM_MEMBER_ERROR';
export const DELETE_TEAM_MEMBER_SUCCESS = 'DELETE_TEAM_MEMBER_SUCCESS';
export const UPDATE_TEAM_MEMBER_SUCCESS = 'UPDATE_TEAM_MEMBER_SUCCESS';
export const UPDATE_TEAM_MEMBER_ERROR = 'UPDATE_TEAM_MEMBER_ERROR';
